#!/usr/bin/env zsh

# SIPを無効にしているため、スクリプト設定を追加した後にパスワードなしで--load-saを実行
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# デフォルトレイアウト：bsp(binary space partioning), stack, flowのいずれか 
yabai -m config layout bsp

# 縦割りなら右に、横割りなら下に新しいウィンドウが生成される
yabai -m config window_placement second_child

# ウインドウのパディング
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# フォーカスのあるウィンドウにマウスをフォーカスさせる
yabai -m config mouse_follows_focus on

# マウスでクリックとドラッグをするための修飾子
yabai -m config mouse_modifier alt
# 左クリックドラッグでウィンドウを動かす
yabai -m config mouse_action1 move
# 右クリックドラッグでウィンドウをリサイズする
yabai -m config mouse_action2 resize
# ウィンドウが他のウィンドウの中央にドロップされた場合、それらを入れ替える (端では分割される)
yabai -m mouse_drop_action swap

# 特定のアプリをyabaiで管理できないようにする
# アプリ名の検索クエリ：yabai -m query --windows | jq ".[] | { App: .app, Title: .title }"
# https://github.com/koekeishiya/yabai/issues/1125
# https://github.com/koekeishiya/yabai/issues/675
yabai -m rule --add app="^System Settings$" manage=off mouse_follows_focus=off
yabai -m rule --add app="^システム環境設定$" manage=off mouse_follows_focus=off
yabai -m rule --add app="^Calculator$" manage=off mouse_follows_focus=off
yabai -m rule --add app="^計算機$" manage=off mouse_follows_focus=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off mouse_follows_focus=off
yabai -m rule --add app="^Cursor Pro$" manage=off mouse_follows_focus=off
yabai -m rule --add app="^Numi$" manage=off mouse_follows_focus=off
yabai -m rule --add app="^iStat Menus Status$" manage=off mouse_follows_focus=off
yabai -m rule --add app="iStat Menus.*" manage=off mouse_follows_focus=off
yabai -m rule --add app="^CleanMyMac X$" manage=off mouse_follows_focus=off
yabai -m rule --add app="^Raycast$" manage=off mouse_follows_focus=off
yabai -m rule --add app="^CleanShot X$" manage=off mouse_follows_focus=off border=off # border=offにしないとエラーが発生（https://github.com/koekeishiya/yabai/issues/1471）
yabai -m rule --add app="^Arc$" subrole="AXSystemDialog" manage=off mouse_follows_focus=off # Arcのダイアログ(動画など)
yabai -m rule --add app="^Arc$" split-child="second_child" manage=off mouse_follows_focus=off # Arcの拡張機能ウインドウ(動画など)
yabai -m rule --add app="^UserNotificationCenter$" manage=off mouse_follows_focus=off # 通知センター
yabai -m rule --add app="^Finder$" manage=off mouse_follows_focus=off 
yabai -m rule --add app="^TickTick$" title="名称未設定" manage=off mouse_follows_focus=off 
yabai -m rule --add app='^Arc$' manage=off # hammerspoonで起動したウインドウは無視させる
yabai -m rule --add app='^Slack$' manage=off # hammerspoonで起動したウインドウは無視させる
yabai -m rule --add app='^Obsidian$' manage=off # hammerspoonで起動したウインドウは無視させる

# ボーダーカラー設定
yabai -m config window_border off
yabai -m config active_window_border_color 0x4DD0E2BE
yabai -m config normal_window_border_color 0xFF000000
yabai -m config insert_feedback_color 0xFF88C0D0

# 全てのフォーカスしていないウィンドウのopacityを0.8にする
yabai -m config window_opacity on
# yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# Sketchybarとの連携
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# 全ディスプレイ上のすべてのスペースの上部に20パディング、下部に0パディングを追加
yabai -m config external_bar all:50:0

echo "yabai configuration loaded.."
