version: "3"
dotenv: ["{{.HOME}}/.dotfiles/.env"]

tasks:
  keytxt:
    silent: true
    cmds:
      # https://unix.stackexchange.com/questions/60213/gpg-asks-for-password-even-with-passphrase
      - gpg --pinentry-mode loopback --passphrase $GPG_PASSPHRASE --decrypt --quiet ~/.dotfiles/app/chatgpt.nvim/key.txt.gpg
