# 共通設定
source ~/.aliases
source ~/.variables

# homebrew setup_homebrewで必要
eval "$(/opt/homebrew/bin/brew shellenv)"

# nodenv setup_nodeで必要
eval "$(nodenv init -)"

# pyenv setup_pythonで必要
eval "$(pyenv init -)"

# Added by LM Studio CLI (lms)
export PATH="$PATH:$HOME/.lmstudio/bin"
# End of LM Studio CLI section
